---
title: "Examen (45 minutes)"
subtitle: "Exploitation et gestion en halieutique"
---

# Contexte 

Un gestionnaire souhaite mettre en place des règles de gestion 
d’une nouvelle ressource halieutique. 
La ressource en question n’est pas une espèce sous gestion européenne, 
et est exploitée localement depuis une vingtaine d’années. 
Le gestionnaire a à sa disposition la liste des navires ciblant l'espèce en question et leurs livres de bord, qui détaillent les captures de l'espèce. 
Une campagne ecosystémique sur la zone de pêche fournit aussi un indice de
biomasse de l'espèce considérée, sur la même période.

# Modèle de Scheafer

On rappelle ici la formulation d'un modèle de dynamique de biomasse, le modèle
de Scheafer:

$$
B_{t=0}=B_0
$$

$$
B_{t+1}=B_{t}+rB_t(1-\frac{B_t}{K})-C_t
$$

avec

- $t$ un indice associé au temps (année)
- $B_t$ la biomasse à l'instant $t$
- $r$ le taux de croissance
- $K$ la biomasse maximale que le système peut atteindre (carrying capacity)
- $C_t$ les captures à l'instant $t$

Exemple : si $B_t$=10t, $r$=0.2, $K$=100t et $C_t$=1, $B_t+1$=10.8
$B_{t+1}=10+0.2*10*(1-10/100)-1=10.8$

Dans ce cadre de modélisation, le rendement maximal durable (RMD) peut être estimé par la formule :

$$
MSY= \frac{rK}{4}
$$

# Question

Dans le contexte donné, et en vous appuyant sur les exemples vus en cours,
rédigez un plan de gestion en indiquant les éléments les plus importants quant à
sa mise en place. 
Vous détaillerez en particulier l'intérêt de mettre en place un tel plan en
lien avec le contexte halieutique européen et le contexte local (à imaginer),
ses objectifs, les données
nécessaires pour mettre en oeuvre ce plan de gestion, les
incertitudes associées, le choix d'un modèle de dynamique de population pour
estimer un niveau d'exploitation durable et les contraintes numériques associées
à l'utilisation d'un tel modèle. Vous pourrez illustrer vos propos à
l'aide des éléments contextuels proposés et à l'aide de graphiques. Vous 
commenterez le plan de gestion en regard des caractéristiques biologiques de l'espèce,
inconnues dans le contexte proposé.


